Repository msys2/MINGW-packages, pull requests merged in 2020-12, with the labels that each got.

#7304 icestorm: add 0.0
  mingw-w64-icestorm/PKGBUILD
Labels: needs-updates

#7273 new package: mtn
  mingw-w64-mtn/001-mtn-3.4.0-makefile.patch
  mingw-w64-mtn/PKGBUILD
Labels: needs-updates

#7020 ExpressCpp
  mingw-w64-expresscpp/0001-Windows-dll-mingw.patch
  mingw-w64-expresscpp/PKGBUILD
Labels: new-package

#7428 dlfcn: Build with CMake also for CMake files (prefer configure/make for the …
  mingw-w64-dlfcn/PKGBUILD
  mingw-w64-ffmpeg/0001-avutil-x86inc-fix-warnings-when-assembling-with-Nasm-2-15.patch
  mingw-w64-ffmpeg/0002-x86-h264_deblock-fix-warning-about-trailing-empty-parameter.patch
  mingw-w64-ffmpeg/0003-x86-vf_blend-fix-warnings-about-trailing-empty-parameters.patch
  mingw-w64-ffmpeg/0004-fix-srt.patch
  mingw-w64-ffmpeg/0005-Win32-Add-path-relocation-to-frei0r-plugins-search.patch
  mingw-w64-ffmpeg/PKGBUILD
  mingw-w64-librdkafka/PKGBUILD
  mingw-w64-mlt/PKGBUILD
Labels: needs-work

#7431 Update luarocks to version 3.4.0
  mingw-w64-lua-luarocks/PKGBUILD
Labels: needs-work
