Repository msys2/MINGW-packages, pull requests merged in 2022-10, with the labels that each got.

#13291 mdbook: New package
  mingw-w64-mdbook/PKGBUILD
Labels: hacktoberfest-accepted

#13292 ruc: New package
  mingw-w64-ruc/0002-ruc-2.4.3-gnu-install-dirs.patch
  mingw-w64-ruc/0003-ruc-2.4.3-libruc-prefix.patch
  mingw-w64-ruc/0004-ruc-2.4.3-codegen-env.patch
  mingw-w64-ruc/PKGBUILD
Labels: hacktoberfest-accepted

#13293 ruc-vm: New package
  mingw-w64-ruc-vm/0001-ruc-vm-1.2-gnu-install-dirs.patch
  mingw-w64-ruc-vm/0002-ruc-vm-1.2-libruc-vm-prefix.patch
  mingw-w64-ruc-vm/PKGBUILD
Labels: hacktoberfest-accepted

#13402 wasm-pack: New package
  mingw-w64-wasm-pack/PKGBUILD
Labels: hacktoberfest-accepted

#13396 kqtquickcharts: New package
  mingw-w64-kqtquickcharts/0001-kqtquickcharts-22.08.1-fix-prefix.patch
  mingw-w64-kqtquickcharts/PKGBUILD
Labels: hacktoberfest-accepted

#13494 ktouch: New package
  mingw-w64-ktouch/0001-ktouch-22.08.1-fix-x11.patch
  mingw-w64-ktouch/PKGBUILD
Labels: hacktoberfest-accepted

#13451 cargo-local-registry: New package
  mingw-w64-cargo-local-registry/PKGBUILD
Labels: hacktoberfest-accepted

#13513 Second attempt at AArch64 Rust
  mingw-w64-rust/0009-build-gnullvm-targets-natively.patch
  mingw-w64-rust/PKGBUILD
Labels: clangarm64

#13184 [new-package] highlight 4.3
  mingw-w64-highlight/001-fix-installation-prefix-and-destdir.patch
  mingw-w64-highlight/002-fix-data-dir-stat.patch
  mingw-w64-highlight/PKGBUILD
Labels: new-package
