Repository msys2/MINGW-packages, pull requests merged in 2022-04, with the labels that each got.

#11143 spice, libvirt and virt-viewer clangarm64
  mingw-w64-appstream-glib/PKGBUILD
  mingw-w64-cantarell-fonts/PKGBUILD
  mingw-w64-dbus-glib/PKGBUILD
  mingw-w64-glib-networking/PKGBUILD
  mingw-w64-gsettings-desktop-schemas/PKGBUILD
  mingw-w64-gst-plugins-good/PKGBUILD
  mingw-w64-icoutils/PKGBUILD
  mingw-w64-libproxy/PKGBUILD
  mingw-w64-libshout/PKGBUILD
  mingw-w64-libsoup/PKGBUILD
  mingw-w64-libvirt-glib/PKGBUILD
  mingw-w64-libvirt/PKGBUILD
  mingw-w64-phodav/PKGBUILD
  mingw-w64-portablexdr/PKGBUILD
  mingw-w64-python-flake8/PKGBUILD
  mingw-w64-python-mccabe/PKGBUILD
  mingw-w64-python-pycodestyle/PKGBUILD
  mingw-w64-python-pyflakes/PKGBUILD
  mingw-w64-spice-gtk/PKGBUILD
  mingw-w64-spice/PKGBUILD
  mingw-w64-taglib/PKGBUILD
  mingw-w64-twolame/PKGBUILD
  mingw-w64-usbredir/PKGBUILD
  mingw-w64-virt-viewer/PKGBUILD
  mingw-w64-wavpack/PKGBUILD
  mingw-w64-yajl/PKGBUILD
Labels: clangarm64

#11088 qt6 clangarm64: everything except doc and static
  mingw-w64-qt6-3d/PKGBUILD
  mingw-w64-qt6-5compat/PKGBUILD
  mingw-w64-qt6-connectivity/PKGBUILD
  mingw-w64-qt6-datavis3d/PKGBUILD
  mingw-w64-qt6-imageformats/PKGBUILD
  mingw-w64-qt6-lottie/PKGBUILD
  mingw-w64-qt6-networkauth/PKGBUILD
  mingw-w64-qt6-positioning/PKGBUILD
  mingw-w64-qt6-quick3d/PKGBUILD
  mingw-w64-qt6-quicktimeline/PKGBUILD
  mingw-w64-qt6-remoteobjects/PKGBUILD
  mingw-w64-qt6-scxml/PKGBUILD
  mingw-w64-qt6-sensors/PKGBUILD
  mingw-w64-qt6-serialbus/PKGBUILD
  mingw-w64-qt6-serialport/PKGBUILD
  mingw-w64-qt6-webchannel/PKGBUILD
  mingw-w64-qt6-websockets/PKGBUILD
Labels: clangarm64

#11383 Add gptfdisk package 1.0.8
  mingw-w64-gptfdisk/0001-makefile-Drop-g-compiler-flag-for-mingw-builds.patch
  mingw-w64-gptfdisk/0002-makefile-Switch-to-building-shared-executables-for-m.patch
  mingw-w64-gptfdisk/0003-makefile-Fix-the-sgdisk-rule-for-mingw-builds.patch
  mingw-w64-gptfdisk/0004-makefile-Specify-std-c-14-for-mingw-builds.patch
  mingw-w64-gptfdisk/0005-makefile-Avoid-absolute-path-in-CXX-for-mingw-builds.patch
  mingw-w64-gptfdisk/0006-makefile-Omit-the-64-suffix-in-the-executable-names.patch
  mingw-w64-gptfdisk/PKGBUILD
Labels: needs-work, new-package

#11098 qt5 clangarm64, part 2
  mingw-w64-qt5-activeqt/PKGBUILD
  mingw-w64-qt5-connectivity/PKGBUILD
  mingw-w64-qt5-gamepad/PKGBUILD
  mingw-w64-qt5-graphicaleffects/PKGBUILD
  mingw-w64-qt5-imageformats/PKGBUILD
  mingw-w64-qt5-lottie/PKGBUILD
  mingw-w64-qt5-multimedia/PKGBUILD
  mingw-w64-qt5-networkauth/PKGBUILD
  mingw-w64-qt5-purchasing/PKGBUILD
  mingw-w64-qt5-quickcontrols/PKGBUILD
  mingw-w64-qt5-quickcontrols2/PKGBUILD
  mingw-w64-qt5-quicktimeline/PKGBUILD
  mingw-w64-qt5-remoteobjects/PKGBUILD
  mingw-w64-qt5-scxml/PKGBUILD
  mingw-w64-qt5-sensors/PKGBUILD
  mingw-w64-qt5-serialbus/PKGBUILD
  mingw-w64-qt5-serialport/PKGBUILD
  mingw-w64-qt5-speech/PKGBUILD
  mingw-w64-qt5-svg/PKGBUILD
  mingw-w64-qt5-tools/PKGBUILD
  mingw-w64-qt5-translations/PKGBUILD
  mingw-w64-qt5-virtualkeyboard/PKGBUILD
  mingw-w64-qt5-webchannel/PKGBUILD
  mingw-w64-qt5-webglplugin/PKGBUILD
  mingw-w64-qt5-websockets/PKGBUILD
  mingw-w64-qt5-webview/PKGBUILD
  mingw-w64-qt5-winextras/PKGBUILD
  mingw-w64-qt5-xmlpatterns/PKGBUILD
Labels: clangarm64

#11206 enable some more clangarm64 packages
  mingw-w64-gnome-common/PKGBUILD
  mingw-w64-libgeotiff/PKGBUILD
  mingw-w64-libsecret/PKGBUILD
  mingw-w64-osm-gps-map/PKGBUILD
  mingw-w64-proj/PKGBUILD
  mingw-w64-python-jsonschema/PKGBUILD
  mingw-w64-python-pyrsistent/PKGBUILD
  mingw-w64-xpm-nox/PKGBUILD
Labels: clangarm64

#11149 enable more clangarm64 packages
  mingw-w64-adol-c/PKGBUILD
  mingw-w64-tesseract-data/PKGBUILD
  mingw-w64-tesseract-ocr/PKGBUILD
Labels: clangarm64

#11440 ptex: update to 2.4.1
  mingw-w64-ptex/0002-ptex-2.1.28-install-dll-correctly.patch
  mingw-w64-ptex/0010-fallback-version-cmake.patch
  mingw-w64-ptex/PKGBUILD
Labels: needs-work

#11504 lldb-mi: Add package
  mingw-w64-lldb-mi/PKGBUILD
Labels: new-package

#11489 new: FrontISTR
  mingw-w64-frontistr/PKGBUILD
Labels: new-package

#11411 enable some more clangarm64 packages
  mingw-w64-discount/PKGBUILD
  mingw-w64-graphicsmagick/PKGBUILD
  mingw-w64-libwmf/PKGBUILD
Labels: clangarm64

#11450 enable some more clangarm64 packages
  mingw-w64-fxc2-git/PKGBUILD
  mingw-w64-qtbinpatcher/PKGBUILD
Labels: clangarm64

#11477 enable some more clangarm64 packages
  mingw-w64-glew/PKGBUILD
  mingw-w64-python-pywavelets/PKGBUILD
Labels: clangarm64

#11478 libnotify: update to 0.7.9, enable clangarm64
  mingw-w64-libnotify/PKGBUILD
  mingw-w64-libnotify/fix-realpath.patch
Labels: clangarm64

#11137 keystone: 0.9.2 (new package)
  mingw-w64-keystone/0001-cmake-install-dir.patch
  mingw-w64-keystone/0002-kstool-win-msys2.patch
  mingw-w64-keystone/PKGBUILD
Labels: new-package

#10677 Add package for fprettify
  mingw-w64-python-configargparse/PKGBUILD
  mingw-w64-python-fprettify/PKGBUILD
Labels: new-package

#11566 raylib: Add package
  mingw-w64-raylib/PKGBUILD
Labels: new-package

#11575 Add amgcl package
  mingw-w64-amgcl/PKGBUILD
Labels: new-package
